name: Deploy website to All-Inkl

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy via lftp
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy to All-Inkl via FTP
        run: |
          lftp -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" "${{ secrets.FTP_SERVER }}" <<EOF
          set ftp:ssl-allow no
          set ftp:passive-mode on
          set net:max-retries 3
          set net:timeout 30
          mirror -R --delete --verbose ./dist/ ${{ secrets.FTP_TARGET_DIR }}
          bye
          EOF
